import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const poppins = localFont({
  src: [
    {
      path: "../public/fonts/Poppins-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Bold.woff2",
      weight: "700",
      style: "normal",
    },
      {
      path: "../public/fonts/Poppins-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    // Add more weights as needed
  ],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
